run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - misspell
    - ineffassign
    - typecheck
    - varcheck
    - unused
    - structcheck
    - deadcode
    - gosimple
    - goimports
    - staticcheck
    - stylecheck
    - gosec
    - asciicheck
    - bodyclose
    - exportloopref
    - rowserrcheck
    - unconvert
    - makezero
    - prealloc
    - predeclared
  skip-files: # 设置不需要检查的go源码文件，支持正则匹配，这里建议包括：_test.go
    - _test.go

linters-settings:
  staticcheck:
    checks: ["S1002","S1004","S1007","S1009","S1010","S1012","S1019","S1020","S1021","S1024","S1030","SA2*","SA3*","SA4009","SA5*","SA6000","SA6001","SA6005", "-SA2002"]
  stylecheck:
    checks: ["-ST1003"]
  gosec:
    severity: "low"
    confidence: "low"
    excludes:
      - G101
service:
  golangci-lint-version: 1.32.2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - rowserrcheck
        - makezero
