// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.6.1
// source: dhcp.proto

package dhcp

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetSubnet4WithIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetSubnet4WithIpRequest) Reset() {
	*x = GetSubnet4WithIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet4WithIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet4WithIpRequest) ProtoMessage() {}

func (x *GetSubnet4WithIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet4WithIpRequest.ProtoReflect.Descriptor instead.
func (*GetSubnet4WithIpRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubnet4WithIpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Subnet4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subnet        string   `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	SubnetId      uint64   `protobuf:"varint,3,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Capacity      uint64   `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	UsedCount     uint64   `protobuf:"varint,5,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	DomainServers []string `protobuf:"bytes,6,rep,name=domain_servers,json=domainServers,proto3" json:"domain_servers,omitempty"`
	Routers       []string `protobuf:"bytes,7,rep,name=routers,proto3" json:"routers,omitempty"`
}

func (x *Subnet4) Reset() {
	*x = Subnet4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subnet4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet4) ProtoMessage() {}

func (x *Subnet4) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet4.ProtoReflect.Descriptor instead.
func (*Subnet4) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{1}
}

func (x *Subnet4) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subnet4) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *Subnet4) GetSubnetId() uint64 {
	if x != nil {
		return x.SubnetId
	}
	return 0
}

func (x *Subnet4) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Subnet4) GetUsedCount() uint64 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *Subnet4) GetDomainServers() []string {
	if x != nil {
		return x.DomainServers
	}
	return nil
}

func (x *Subnet4) GetRouters() []string {
	if x != nil {
		return x.Routers
	}
	return nil
}

type GetSubnet4WithIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool                `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Subnets map[string]*Subnet4 `protobuf:"bytes,2,rep,name=subnets,proto3" json:"subnets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnet4WithIpResponse) Reset() {
	*x = GetSubnet4WithIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet4WithIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet4WithIpResponse) ProtoMessage() {}

func (x *GetSubnet4WithIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet4WithIpResponse.ProtoReflect.Descriptor instead.
func (*GetSubnet4WithIpResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubnet4WithIpResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnet4WithIpResponse) GetSubnets() map[string]*Subnet4 {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type GetSubnet6WithIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetSubnet6WithIpRequest) Reset() {
	*x = GetSubnet6WithIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet6WithIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet6WithIpRequest) ProtoMessage() {}

func (x *GetSubnet6WithIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet6WithIpRequest.ProtoReflect.Descriptor instead.
func (*GetSubnet6WithIpRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubnet6WithIpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Subnet6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subnet        string   `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	SubnetId      uint64   `protobuf:"varint,3,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Capacity      uint64   `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	UsedCount     uint64   `protobuf:"varint,5,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	DomainServers []string `protobuf:"bytes,6,rep,name=domain_servers,json=domainServers,proto3" json:"domain_servers,omitempty"`
}

func (x *Subnet6) Reset() {
	*x = Subnet6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subnet6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet6) ProtoMessage() {}

func (x *Subnet6) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet6.ProtoReflect.Descriptor instead.
func (*Subnet6) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{4}
}

func (x *Subnet6) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subnet6) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *Subnet6) GetSubnetId() uint64 {
	if x != nil {
		return x.SubnetId
	}
	return 0
}

func (x *Subnet6) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Subnet6) GetUsedCount() uint64 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *Subnet6) GetDomainServers() []string {
	if x != nil {
		return x.DomainServers
	}
	return nil
}

type GetSubnet6WithIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool                `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Subnets map[string]*Subnet6 `protobuf:"bytes,2,rep,name=subnets,proto3" json:"subnets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnet6WithIpResponse) Reset() {
	*x = GetSubnet6WithIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet6WithIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet6WithIpResponse) ProtoMessage() {}

func (x *GetSubnet6WithIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet6WithIpResponse.ProtoReflect.Descriptor instead.
func (*GetSubnet6WithIpResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubnet6WithIpResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnet6WithIpResponse) GetSubnets() map[string]*Subnet6 {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type GetSubnets4WithIpsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ips []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *GetSubnets4WithIpsRequest) Reset() {
	*x = GetSubnets4WithIpsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets4WithIpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets4WithIpsRequest) ProtoMessage() {}

func (x *GetSubnets4WithIpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets4WithIpsRequest.ProtoReflect.Descriptor instead.
func (*GetSubnets4WithIpsRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{6}
}

func (x *GetSubnets4WithIpsRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type GetSubnets4WithIpsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool                `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Subnets map[string]*Subnet4 `protobuf:"bytes,2,rep,name=subnets,proto3" json:"subnets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnets4WithIpsResponse) Reset() {
	*x = GetSubnets4WithIpsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets4WithIpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets4WithIpsResponse) ProtoMessage() {}

func (x *GetSubnets4WithIpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets4WithIpsResponse.ProtoReflect.Descriptor instead.
func (*GetSubnets4WithIpsResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{7}
}

func (x *GetSubnets4WithIpsResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnets4WithIpsResponse) GetSubnets() map[string]*Subnet4 {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type GetSubnets6WithIpsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ips []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *GetSubnets6WithIpsRequest) Reset() {
	*x = GetSubnets6WithIpsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets6WithIpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets6WithIpsRequest) ProtoMessage() {}

func (x *GetSubnets6WithIpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets6WithIpsRequest.ProtoReflect.Descriptor instead.
func (*GetSubnets6WithIpsRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubnets6WithIpsRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type GetSubnets6WithIpsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool                `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Subnets map[string]*Subnet6 `protobuf:"bytes,2,rep,name=subnets,proto3" json:"subnets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnets6WithIpsResponse) Reset() {
	*x = GetSubnets6WithIpsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets6WithIpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets6WithIpsResponse) ProtoMessage() {}

func (x *GetSubnets6WithIpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets6WithIpsResponse.ProtoReflect.Descriptor instead.
func (*GetSubnets6WithIpsResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{9}
}

func (x *GetSubnets6WithIpsResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnets6WithIpsResponse) GetSubnets() map[string]*Subnet6 {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type GetSubnet4AndLease4WithIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetSubnet4AndLease4WithIpRequest) Reset() {
	*x = GetSubnet4AndLease4WithIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet4AndLease4WithIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet4AndLease4WithIpRequest) ProtoMessage() {}

func (x *GetSubnet4AndLease4WithIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet4AndLease4WithIpRequest.ProtoReflect.Descriptor instead.
func (*GetSubnet4AndLease4WithIpRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{10}
}

func (x *GetSubnet4AndLease4WithIpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Lease4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address               string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	HwAddress             string `protobuf:"bytes,2,opt,name=hw_address,json=hwAddress,proto3" json:"hw_address,omitempty"`
	HwAddressOrganization string `protobuf:"bytes,3,opt,name=hw_address_organization,json=hwAddressOrganization,proto3" json:"hw_address_organization,omitempty"`
	ClientId              string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ValidLifetime         uint32 `protobuf:"varint,5,opt,name=valid_lifetime,json=validLifetime,proto3" json:"valid_lifetime,omitempty"`
	Expire                string `protobuf:"bytes,6,opt,name=expire,proto3" json:"expire,omitempty"`
	Hostname              string `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	VendorId              string `protobuf:"bytes,8,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	OperatingSystem       string `protobuf:"bytes,9,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	ClientType            string `protobuf:"bytes,10,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	LeaseState            string `protobuf:"bytes,11,opt,name=lease_state,json=leaseState,proto3" json:"lease_state,omitempty"`
}

func (x *Lease4) Reset() {
	*x = Lease4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lease4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease4) ProtoMessage() {}

func (x *Lease4) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease4.ProtoReflect.Descriptor instead.
func (*Lease4) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{11}
}

func (x *Lease4) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Lease4) GetHwAddress() string {
	if x != nil {
		return x.HwAddress
	}
	return ""
}

func (x *Lease4) GetHwAddressOrganization() string {
	if x != nil {
		return x.HwAddressOrganization
	}
	return ""
}

func (x *Lease4) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Lease4) GetValidLifetime() uint32 {
	if x != nil {
		return x.ValidLifetime
	}
	return 0
}

func (x *Lease4) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

func (x *Lease4) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Lease4) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *Lease4) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *Lease4) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *Lease4) GetLeaseState() string {
	if x != nil {
		return x.LeaseState
	}
	return ""
}

type Ipv4Information struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AddressType string   `protobuf:"bytes,2,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	Subnet      *Subnet4 `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Lease       *Lease4  `protobuf:"bytes,4,opt,name=lease,proto3" json:"lease,omitempty"`
}

func (x *Ipv4Information) Reset() {
	*x = Ipv4Information{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv4Information) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv4Information) ProtoMessage() {}

func (x *Ipv4Information) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv4Information.ProtoReflect.Descriptor instead.
func (*Ipv4Information) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{12}
}

func (x *Ipv4Information) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Ipv4Information) GetAddressType() string {
	if x != nil {
		return x.AddressType
	}
	return ""
}

func (x *Ipv4Information) GetSubnet() *Subnet4 {
	if x != nil {
		return x.Subnet
	}
	return nil
}

func (x *Ipv4Information) GetLease() *Lease4 {
	if x != nil {
		return x.Lease
	}
	return nil
}

type GetSubnet4AndLease4WithIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed          bool                        `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Ipv4Informations map[string]*Ipv4Information `protobuf:"bytes,2,rep,name=ipv4_informations,json=ipv4Informations,proto3" json:"ipv4_informations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnet4AndLease4WithIpResponse) Reset() {
	*x = GetSubnet4AndLease4WithIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet4AndLease4WithIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet4AndLease4WithIpResponse) ProtoMessage() {}

func (x *GetSubnet4AndLease4WithIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet4AndLease4WithIpResponse.ProtoReflect.Descriptor instead.
func (*GetSubnet4AndLease4WithIpResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{13}
}

func (x *GetSubnet4AndLease4WithIpResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnet4AndLease4WithIpResponse) GetIpv4Informations() map[string]*Ipv4Information {
	if x != nil {
		return x.Ipv4Informations
	}
	return nil
}

type GetSubnet6AndLease6WithIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetSubnet6AndLease6WithIpRequest) Reset() {
	*x = GetSubnet6AndLease6WithIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet6AndLease6WithIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet6AndLease6WithIpRequest) ProtoMessage() {}

func (x *GetSubnet6AndLease6WithIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet6AndLease6WithIpRequest.ProtoReflect.Descriptor instead.
func (*GetSubnet6AndLease6WithIpRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{14}
}

func (x *GetSubnet6AndLease6WithIpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Lease6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address               string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLen             uint32 `protobuf:"varint,2,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	Duid                  string `protobuf:"bytes,3,opt,name=duid,proto3" json:"duid,omitempty"`
	Iaid                  uint32 `protobuf:"varint,4,opt,name=iaid,proto3" json:"iaid,omitempty"`
	PreferredLifetime     uint32 `protobuf:"varint,5,opt,name=preferred_lifetime,json=preferredLifetime,proto3" json:"preferred_lifetime,omitempty"`
	ValidLifetime         uint32 `protobuf:"varint,6,opt,name=valid_lifetime,json=validLifetime,proto3" json:"valid_lifetime,omitempty"`
	Expire                string `protobuf:"bytes,7,opt,name=expire,proto3" json:"expire,omitempty"`
	HwAddress             string `protobuf:"bytes,8,opt,name=hw_address,json=hwAddress,proto3" json:"hw_address,omitempty"`
	HwAddressType         string `protobuf:"bytes,9,opt,name=hw_address_type,json=hwAddressType,proto3" json:"hw_address_type,omitempty"`
	HwAddressSource       string `protobuf:"bytes,10,opt,name=hw_address_source,json=hwAddressSource,proto3" json:"hw_address_source,omitempty"`
	HwAddressOrganization string `protobuf:"bytes,11,opt,name=hw_address_organization,json=hwAddressOrganization,proto3" json:"hw_address_organization,omitempty"`
	LeaseType             string `protobuf:"bytes,12,opt,name=lease_type,json=leaseType,proto3" json:"lease_type,omitempty"`
	Hostname              string `protobuf:"bytes,13,opt,name=hostname,proto3" json:"hostname,omitempty"`
	VendorId              string `protobuf:"bytes,14,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	OperatingSystem       string `protobuf:"bytes,15,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	ClientType            string `protobuf:"bytes,16,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	LeaseState            string `protobuf:"bytes,17,opt,name=lease_state,json=leaseState,proto3" json:"lease_state,omitempty"`
}

func (x *Lease6) Reset() {
	*x = Lease6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lease6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease6) ProtoMessage() {}

func (x *Lease6) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease6.ProtoReflect.Descriptor instead.
func (*Lease6) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{15}
}

func (x *Lease6) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Lease6) GetPrefixLen() uint32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *Lease6) GetDuid() string {
	if x != nil {
		return x.Duid
	}
	return ""
}

func (x *Lease6) GetIaid() uint32 {
	if x != nil {
		return x.Iaid
	}
	return 0
}

func (x *Lease6) GetPreferredLifetime() uint32 {
	if x != nil {
		return x.PreferredLifetime
	}
	return 0
}

func (x *Lease6) GetValidLifetime() uint32 {
	if x != nil {
		return x.ValidLifetime
	}
	return 0
}

func (x *Lease6) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

func (x *Lease6) GetHwAddress() string {
	if x != nil {
		return x.HwAddress
	}
	return ""
}

func (x *Lease6) GetHwAddressType() string {
	if x != nil {
		return x.HwAddressType
	}
	return ""
}

func (x *Lease6) GetHwAddressSource() string {
	if x != nil {
		return x.HwAddressSource
	}
	return ""
}

func (x *Lease6) GetHwAddressOrganization() string {
	if x != nil {
		return x.HwAddressOrganization
	}
	return ""
}

func (x *Lease6) GetLeaseType() string {
	if x != nil {
		return x.LeaseType
	}
	return ""
}

func (x *Lease6) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Lease6) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *Lease6) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *Lease6) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *Lease6) GetLeaseState() string {
	if x != nil {
		return x.LeaseState
	}
	return ""
}

type Ipv6Information struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AddressType string   `protobuf:"bytes,2,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	Subnet      *Subnet6 `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Lease       *Lease6  `protobuf:"bytes,4,opt,name=lease,proto3" json:"lease,omitempty"`
}

func (x *Ipv6Information) Reset() {
	*x = Ipv6Information{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6Information) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6Information) ProtoMessage() {}

func (x *Ipv6Information) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6Information.ProtoReflect.Descriptor instead.
func (*Ipv6Information) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{16}
}

func (x *Ipv6Information) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Ipv6Information) GetAddressType() string {
	if x != nil {
		return x.AddressType
	}
	return ""
}

func (x *Ipv6Information) GetSubnet() *Subnet6 {
	if x != nil {
		return x.Subnet
	}
	return nil
}

func (x *Ipv6Information) GetLease() *Lease6 {
	if x != nil {
		return x.Lease
	}
	return nil
}

type GetSubnet6AndLease6WithIpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed          bool                        `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Ipv6Informations map[string]*Ipv6Information `protobuf:"bytes,2,rep,name=ipv6_informations,json=ipv6Informations,proto3" json:"ipv6_informations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnet6AndLease6WithIpResponse) Reset() {
	*x = GetSubnet6AndLease6WithIpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnet6AndLease6WithIpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnet6AndLease6WithIpResponse) ProtoMessage() {}

func (x *GetSubnet6AndLease6WithIpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnet6AndLease6WithIpResponse.ProtoReflect.Descriptor instead.
func (*GetSubnet6AndLease6WithIpResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubnet6AndLease6WithIpResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnet6AndLease6WithIpResponse) GetIpv6Informations() map[string]*Ipv6Information {
	if x != nil {
		return x.Ipv6Informations
	}
	return nil
}

type GetSubnets4AndLeases4WithIpsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ips []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *GetSubnets4AndLeases4WithIpsRequest) Reset() {
	*x = GetSubnets4AndLeases4WithIpsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets4AndLeases4WithIpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets4AndLeases4WithIpsRequest) ProtoMessage() {}

func (x *GetSubnets4AndLeases4WithIpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets4AndLeases4WithIpsRequest.ProtoReflect.Descriptor instead.
func (*GetSubnets4AndLeases4WithIpsRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{18}
}

func (x *GetSubnets4AndLeases4WithIpsRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type GetSubnets4AndLeases4WithIpsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed          bool                        `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Ipv4Informations map[string]*Ipv4Information `protobuf:"bytes,2,rep,name=ipv4_informations,json=ipv4Informations,proto3" json:"ipv4_informations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnets4AndLeases4WithIpsResponse) Reset() {
	*x = GetSubnets4AndLeases4WithIpsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets4AndLeases4WithIpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets4AndLeases4WithIpsResponse) ProtoMessage() {}

func (x *GetSubnets4AndLeases4WithIpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets4AndLeases4WithIpsResponse.ProtoReflect.Descriptor instead.
func (*GetSubnets4AndLeases4WithIpsResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{19}
}

func (x *GetSubnets4AndLeases4WithIpsResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnets4AndLeases4WithIpsResponse) GetIpv4Informations() map[string]*Ipv4Information {
	if x != nil {
		return x.Ipv4Informations
	}
	return nil
}

type GetSubnets6AndLeases6WithIpsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ips []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *GetSubnets6AndLeases6WithIpsRequest) Reset() {
	*x = GetSubnets6AndLeases6WithIpsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets6AndLeases6WithIpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets6AndLeases6WithIpsRequest) ProtoMessage() {}

func (x *GetSubnets6AndLeases6WithIpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets6AndLeases6WithIpsRequest.ProtoReflect.Descriptor instead.
func (*GetSubnets6AndLeases6WithIpsRequest) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{20}
}

func (x *GetSubnets6AndLeases6WithIpsRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type GetSubnets6AndLeases6WithIpsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed          bool                        `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Ipv6Informations map[string]*Ipv6Information `protobuf:"bytes,2,rep,name=ipv6_informations,json=ipv6Informations,proto3" json:"ipv6_informations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetSubnets6AndLeases6WithIpsResponse) Reset() {
	*x = GetSubnets6AndLeases6WithIpsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dhcp_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubnets6AndLeases6WithIpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnets6AndLeases6WithIpsResponse) ProtoMessage() {}

func (x *GetSubnets6AndLeases6WithIpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhcp_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnets6AndLeases6WithIpsResponse.ProtoReflect.Descriptor instead.
func (*GetSubnets6AndLeases6WithIpsResponse) Descriptor() ([]byte, []int) {
	return file_dhcp_proto_rawDescGZIP(), []int{21}
}

func (x *GetSubnets6AndLeases6WithIpsResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *GetSubnets6AndLeases6WithIpsResponse) GetIpv6Informations() map[string]*Ipv6Information {
	if x != nil {
		return x.Ipv6Informations
	}
	return nil
}

var File_dhcp_proto protoreflect.FileDescriptor

var file_dhcp_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x68, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0xca, 0x01, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x40, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x1a, 0x44, 0x0a,
	0x0c, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x29, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0xb0,
	0x01, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x73, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x75, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x22, 0xbc, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36,
	0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x40, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x1a, 0x44, 0x0a, 0x0c, 0x53, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x36, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x2d, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22,
	0xc0, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x1a, 0x44, 0x0a, 0x0c,
	0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x2d, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73,
	0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70,
	0x73, 0x22, 0xc0, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73,
	0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x1a, 0x44,
	0x0a, 0x0c, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0xfb, 0x02, 0x0a, 0x06, 0x4c, 0x65, 0x61,
	0x73, 0x65, 0x34, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x68, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x68, 0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x36, 0x0a, 0x17,
	0x68, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x68,
	0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0f, 0x49, 0x70, 0x76, 0x34, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x34, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x34, 0x52, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x22, 0xfb, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74,
	0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x34,
	0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x65, 0x0a, 0x11, 0x69, 0x70, 0x76, 0x34,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34,
	0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x70, 0x76, 0x34, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x69,
	0x70, 0x76, 0x34, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x55, 0x0a, 0x15, 0x49, 0x70, 0x76, 0x34, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x70, 0x76, 0x34,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x36, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x36, 0x57, 0x69, 0x74,
	0x68, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0xc7, 0x04, 0x0a, 0x06, 0x4c,
	0x65, 0x61, 0x73, 0x65, 0x36, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x4c, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x75,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x61, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x69, 0x61, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x66,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6c,
	0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x77, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x68, 0x77,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x68,
	0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x68, 0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x68, 0x77, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x68, 0x77, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0f, 0x49, 0x70, 0x76, 0x36, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x52,
	0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x36, 0x52,
	0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x22, 0xfb, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x36, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x36, 0x57, 0x69,
	0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x65, 0x0a, 0x11, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x38, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x41, 0x6e,
	0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x70, 0x76, 0x36, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x69, 0x70, 0x76,
	0x36, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x55, 0x0a,
	0x15, 0x49, 0x70, 0x76, 0x36, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x70, 0x76, 0x36, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x37, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x73, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x34, 0x57, 0x69, 0x74,
	0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22, 0x81, 0x02,
	0x0a, 0x24, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34, 0x41, 0x6e, 0x64,
	0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64,
	0x12, 0x68, 0x0a, 0x11, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73,
	0x65, 0x73, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x49, 0x70, 0x76, 0x34, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x69, 0x70, 0x76, 0x34, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x55, 0x0a, 0x15, 0x49, 0x70,
	0x76, 0x34, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x70, 0x76, 0x34, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x37, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x36,
	0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22, 0x81, 0x02, 0x0a, 0x24, 0x47,
	0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x36, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61,
	0x73, 0x65, 0x73, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x12, 0x68, 0x0a,
	0x11, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x73, 0x36, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x36,
	0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x49, 0x70, 0x76, 0x36, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x69, 0x70, 0x76, 0x36, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x55, 0x0a, 0x15, 0x49, 0x70, 0x76, 0x36, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x49, 0x70, 0x76, 0x36, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xdf,
	0x05, 0x0a, 0x0b, 0x44, 0x68, 0x63, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x57, 0x69, 0x74, 0x68,
	0x49, 0x70, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x12, 0x18, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x12, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x73, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34,
	0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x36, 0x57, 0x69,
	0x74, 0x68, 0x49, 0x70, 0x73, 0x12, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x73, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x36, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x41, 0x6e, 0x64, 0x4c,
	0x65, 0x61, 0x73, 0x65, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x12, 0x21, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65,
	0x61, 0x73, 0x65, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x62, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36,
	0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x12,
	0x21, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x41, 0x6e, 0x64, 0x4c,
	0x65, 0x61, 0x73, 0x65, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x41,
	0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x73, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x34, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x12, 0x24, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x73, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x34, 0x57, 0x69,
	0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x34, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61,
	0x73, 0x65, 0x73, 0x34, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x73, 0x36, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x36, 0x57, 0x69, 0x74, 0x68,
	0x49, 0x70, 0x73, 0x12, 0x24, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73,
	0x36, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x36, 0x57, 0x69, 0x74, 0x68, 0x49,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x36, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73,
	0x36, 0x57, 0x69, 0x74, 0x68, 0x49, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x64, 0x68, 0x63, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dhcp_proto_rawDescOnce sync.Once
	file_dhcp_proto_rawDescData = file_dhcp_proto_rawDesc
)

func file_dhcp_proto_rawDescGZIP() []byte {
	file_dhcp_proto_rawDescOnce.Do(func() {
		file_dhcp_proto_rawDescData = protoimpl.X.CompressGZIP(file_dhcp_proto_rawDescData)
	})
	return file_dhcp_proto_rawDescData
}

var file_dhcp_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_dhcp_proto_goTypes = []interface{}{
	(*GetSubnet4WithIpRequest)(nil),              // 0: GetSubnet4WithIpRequest
	(*Subnet4)(nil),                              // 1: Subnet4
	(*GetSubnet4WithIpResponse)(nil),             // 2: GetSubnet4WithIpResponse
	(*GetSubnet6WithIpRequest)(nil),              // 3: GetSubnet6WithIpRequest
	(*Subnet6)(nil),                              // 4: Subnet6
	(*GetSubnet6WithIpResponse)(nil),             // 5: GetSubnet6WithIpResponse
	(*GetSubnets4WithIpsRequest)(nil),            // 6: GetSubnets4WithIpsRequest
	(*GetSubnets4WithIpsResponse)(nil),           // 7: GetSubnets4WithIpsResponse
	(*GetSubnets6WithIpsRequest)(nil),            // 8: GetSubnets6WithIpsRequest
	(*GetSubnets6WithIpsResponse)(nil),           // 9: GetSubnets6WithIpsResponse
	(*GetSubnet4AndLease4WithIpRequest)(nil),     // 10: GetSubnet4AndLease4WithIpRequest
	(*Lease4)(nil),                               // 11: Lease4
	(*Ipv4Information)(nil),                      // 12: Ipv4Information
	(*GetSubnet4AndLease4WithIpResponse)(nil),    // 13: GetSubnet4AndLease4WithIpResponse
	(*GetSubnet6AndLease6WithIpRequest)(nil),     // 14: GetSubnet6AndLease6WithIpRequest
	(*Lease6)(nil),                               // 15: Lease6
	(*Ipv6Information)(nil),                      // 16: Ipv6Information
	(*GetSubnet6AndLease6WithIpResponse)(nil),    // 17: GetSubnet6AndLease6WithIpResponse
	(*GetSubnets4AndLeases4WithIpsRequest)(nil),  // 18: GetSubnets4AndLeases4WithIpsRequest
	(*GetSubnets4AndLeases4WithIpsResponse)(nil), // 19: GetSubnets4AndLeases4WithIpsResponse
	(*GetSubnets6AndLeases6WithIpsRequest)(nil),  // 20: GetSubnets6AndLeases6WithIpsRequest
	(*GetSubnets6AndLeases6WithIpsResponse)(nil), // 21: GetSubnets6AndLeases6WithIpsResponse
	nil, // 22: GetSubnet4WithIpResponse.SubnetsEntry
	nil, // 23: GetSubnet6WithIpResponse.SubnetsEntry
	nil, // 24: GetSubnets4WithIpsResponse.SubnetsEntry
	nil, // 25: GetSubnets6WithIpsResponse.SubnetsEntry
	nil, // 26: GetSubnet4AndLease4WithIpResponse.Ipv4InformationsEntry
	nil, // 27: GetSubnet6AndLease6WithIpResponse.Ipv6InformationsEntry
	nil, // 28: GetSubnets4AndLeases4WithIpsResponse.Ipv4InformationsEntry
	nil, // 29: GetSubnets6AndLeases6WithIpsResponse.Ipv6InformationsEntry
}
var file_dhcp_proto_depIdxs = []int32{
	22, // 0: GetSubnet4WithIpResponse.subnets:type_name -> GetSubnet4WithIpResponse.SubnetsEntry
	23, // 1: GetSubnet6WithIpResponse.subnets:type_name -> GetSubnet6WithIpResponse.SubnetsEntry
	24, // 2: GetSubnets4WithIpsResponse.subnets:type_name -> GetSubnets4WithIpsResponse.SubnetsEntry
	25, // 3: GetSubnets6WithIpsResponse.subnets:type_name -> GetSubnets6WithIpsResponse.SubnetsEntry
	1,  // 4: Ipv4Information.subnet:type_name -> Subnet4
	11, // 5: Ipv4Information.lease:type_name -> Lease4
	26, // 6: GetSubnet4AndLease4WithIpResponse.ipv4_informations:type_name -> GetSubnet4AndLease4WithIpResponse.Ipv4InformationsEntry
	4,  // 7: Ipv6Information.subnet:type_name -> Subnet6
	15, // 8: Ipv6Information.lease:type_name -> Lease6
	27, // 9: GetSubnet6AndLease6WithIpResponse.ipv6_informations:type_name -> GetSubnet6AndLease6WithIpResponse.Ipv6InformationsEntry
	28, // 10: GetSubnets4AndLeases4WithIpsResponse.ipv4_informations:type_name -> GetSubnets4AndLeases4WithIpsResponse.Ipv4InformationsEntry
	29, // 11: GetSubnets6AndLeases6WithIpsResponse.ipv6_informations:type_name -> GetSubnets6AndLeases6WithIpsResponse.Ipv6InformationsEntry
	1,  // 12: GetSubnet4WithIpResponse.SubnetsEntry.value:type_name -> Subnet4
	4,  // 13: GetSubnet6WithIpResponse.SubnetsEntry.value:type_name -> Subnet6
	1,  // 14: GetSubnets4WithIpsResponse.SubnetsEntry.value:type_name -> Subnet4
	4,  // 15: GetSubnets6WithIpsResponse.SubnetsEntry.value:type_name -> Subnet6
	12, // 16: GetSubnet4AndLease4WithIpResponse.Ipv4InformationsEntry.value:type_name -> Ipv4Information
	16, // 17: GetSubnet6AndLease6WithIpResponse.Ipv6InformationsEntry.value:type_name -> Ipv6Information
	12, // 18: GetSubnets4AndLeases4WithIpsResponse.Ipv4InformationsEntry.value:type_name -> Ipv4Information
	16, // 19: GetSubnets6AndLeases6WithIpsResponse.Ipv6InformationsEntry.value:type_name -> Ipv6Information
	0,  // 20: DhcpService.GetSubnet4WithIp:input_type -> GetSubnet4WithIpRequest
	3,  // 21: DhcpService.GetSubnet6WithIp:input_type -> GetSubnet6WithIpRequest
	6,  // 22: DhcpService.GetSubnets4WithIps:input_type -> GetSubnets4WithIpsRequest
	8,  // 23: DhcpService.GetSubnets6WithIps:input_type -> GetSubnets6WithIpsRequest
	10, // 24: DhcpService.GetSubnet4AndLease4WithIp:input_type -> GetSubnet4AndLease4WithIpRequest
	14, // 25: DhcpService.GetSubnet6AndLease6WithIp:input_type -> GetSubnet6AndLease6WithIpRequest
	18, // 26: DhcpService.GetSubnets4AndLeases4WithIps:input_type -> GetSubnets4AndLeases4WithIpsRequest
	20, // 27: DhcpService.GetSubnets6AndLeases6WithIps:input_type -> GetSubnets6AndLeases6WithIpsRequest
	2,  // 28: DhcpService.GetSubnet4WithIp:output_type -> GetSubnet4WithIpResponse
	5,  // 29: DhcpService.GetSubnet6WithIp:output_type -> GetSubnet6WithIpResponse
	7,  // 30: DhcpService.GetSubnets4WithIps:output_type -> GetSubnets4WithIpsResponse
	9,  // 31: DhcpService.GetSubnets6WithIps:output_type -> GetSubnets6WithIpsResponse
	13, // 32: DhcpService.GetSubnet4AndLease4WithIp:output_type -> GetSubnet4AndLease4WithIpResponse
	17, // 33: DhcpService.GetSubnet6AndLease6WithIp:output_type -> GetSubnet6AndLease6WithIpResponse
	19, // 34: DhcpService.GetSubnets4AndLeases4WithIps:output_type -> GetSubnets4AndLeases4WithIpsResponse
	21, // 35: DhcpService.GetSubnets6AndLeases6WithIps:output_type -> GetSubnets6AndLeases6WithIpsResponse
	28, // [28:36] is the sub-list for method output_type
	20, // [20:28] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_dhcp_proto_init() }
func file_dhcp_proto_init() {
	if File_dhcp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dhcp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet4WithIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subnet4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet4WithIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet6WithIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subnet6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet6WithIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets4WithIpsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets4WithIpsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets6WithIpsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets6WithIpsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet4AndLease4WithIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lease4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv4Information); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet4AndLease4WithIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet6AndLease6WithIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lease6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6Information); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnet6AndLease6WithIpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets4AndLeases4WithIpsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets4AndLeases4WithIpsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets6AndLeases6WithIpsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dhcp_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubnets6AndLeases6WithIpsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dhcp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dhcp_proto_goTypes,
		DependencyIndexes: file_dhcp_proto_depIdxs,
		MessageInfos:      file_dhcp_proto_msgTypes,
	}.Build()
	File_dhcp_proto = out.File
	file_dhcp_proto_rawDesc = nil
	file_dhcp_proto_goTypes = nil
	file_dhcp_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DhcpServiceClient is the client API for DhcpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DhcpServiceClient interface {
	GetSubnet4WithIp(ctx context.Context, in *GetSubnet4WithIpRequest, opts ...grpc.CallOption) (*GetSubnet4WithIpResponse, error)
	GetSubnet6WithIp(ctx context.Context, in *GetSubnet6WithIpRequest, opts ...grpc.CallOption) (*GetSubnet6WithIpResponse, error)
	GetSubnets4WithIps(ctx context.Context, in *GetSubnets4WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets4WithIpsResponse, error)
	GetSubnets6WithIps(ctx context.Context, in *GetSubnets6WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets6WithIpsResponse, error)
	GetSubnet4AndLease4WithIp(ctx context.Context, in *GetSubnet4AndLease4WithIpRequest, opts ...grpc.CallOption) (*GetSubnet4AndLease4WithIpResponse, error)
	GetSubnet6AndLease6WithIp(ctx context.Context, in *GetSubnet6AndLease6WithIpRequest, opts ...grpc.CallOption) (*GetSubnet6AndLease6WithIpResponse, error)
	GetSubnets4AndLeases4WithIps(ctx context.Context, in *GetSubnets4AndLeases4WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets4AndLeases4WithIpsResponse, error)
	GetSubnets6AndLeases6WithIps(ctx context.Context, in *GetSubnets6AndLeases6WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets6AndLeases6WithIpsResponse, error)
}

type dhcpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDhcpServiceClient(cc grpc.ClientConnInterface) DhcpServiceClient {
	return &dhcpServiceClient{cc}
}

func (c *dhcpServiceClient) GetSubnet4WithIp(ctx context.Context, in *GetSubnet4WithIpRequest, opts ...grpc.CallOption) (*GetSubnet4WithIpResponse, error) {
	out := new(GetSubnet4WithIpResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnet4WithIp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) GetSubnet6WithIp(ctx context.Context, in *GetSubnet6WithIpRequest, opts ...grpc.CallOption) (*GetSubnet6WithIpResponse, error) {
	out := new(GetSubnet6WithIpResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnet6WithIp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) GetSubnets4WithIps(ctx context.Context, in *GetSubnets4WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets4WithIpsResponse, error) {
	out := new(GetSubnets4WithIpsResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnets4WithIps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) GetSubnets6WithIps(ctx context.Context, in *GetSubnets6WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets6WithIpsResponse, error) {
	out := new(GetSubnets6WithIpsResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnets6WithIps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) GetSubnet4AndLease4WithIp(ctx context.Context, in *GetSubnet4AndLease4WithIpRequest, opts ...grpc.CallOption) (*GetSubnet4AndLease4WithIpResponse, error) {
	out := new(GetSubnet4AndLease4WithIpResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnet4AndLease4WithIp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) GetSubnet6AndLease6WithIp(ctx context.Context, in *GetSubnet6AndLease6WithIpRequest, opts ...grpc.CallOption) (*GetSubnet6AndLease6WithIpResponse, error) {
	out := new(GetSubnet6AndLease6WithIpResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnet6AndLease6WithIp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) GetSubnets4AndLeases4WithIps(ctx context.Context, in *GetSubnets4AndLeases4WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets4AndLeases4WithIpsResponse, error) {
	out := new(GetSubnets4AndLeases4WithIpsResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnets4AndLeases4WithIps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) GetSubnets6AndLeases6WithIps(ctx context.Context, in *GetSubnets6AndLeases6WithIpsRequest, opts ...grpc.CallOption) (*GetSubnets6AndLeases6WithIpsResponse, error) {
	out := new(GetSubnets6AndLeases6WithIpsResponse)
	err := c.cc.Invoke(ctx, "/DhcpService/GetSubnets6AndLeases6WithIps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DhcpServiceServer is the server API for DhcpService service.
type DhcpServiceServer interface {
	GetSubnet4WithIp(context.Context, *GetSubnet4WithIpRequest) (*GetSubnet4WithIpResponse, error)
	GetSubnet6WithIp(context.Context, *GetSubnet6WithIpRequest) (*GetSubnet6WithIpResponse, error)
	GetSubnets4WithIps(context.Context, *GetSubnets4WithIpsRequest) (*GetSubnets4WithIpsResponse, error)
	GetSubnets6WithIps(context.Context, *GetSubnets6WithIpsRequest) (*GetSubnets6WithIpsResponse, error)
	GetSubnet4AndLease4WithIp(context.Context, *GetSubnet4AndLease4WithIpRequest) (*GetSubnet4AndLease4WithIpResponse, error)
	GetSubnet6AndLease6WithIp(context.Context, *GetSubnet6AndLease6WithIpRequest) (*GetSubnet6AndLease6WithIpResponse, error)
	GetSubnets4AndLeases4WithIps(context.Context, *GetSubnets4AndLeases4WithIpsRequest) (*GetSubnets4AndLeases4WithIpsResponse, error)
	GetSubnets6AndLeases6WithIps(context.Context, *GetSubnets6AndLeases6WithIpsRequest) (*GetSubnets6AndLeases6WithIpsResponse, error)
}

// UnimplementedDhcpServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDhcpServiceServer struct {
}

func (*UnimplementedDhcpServiceServer) GetSubnet4WithIp(context.Context, *GetSubnet4WithIpRequest) (*GetSubnet4WithIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnet4WithIp not implemented")
}
func (*UnimplementedDhcpServiceServer) GetSubnet6WithIp(context.Context, *GetSubnet6WithIpRequest) (*GetSubnet6WithIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnet6WithIp not implemented")
}
func (*UnimplementedDhcpServiceServer) GetSubnets4WithIps(context.Context, *GetSubnets4WithIpsRequest) (*GetSubnets4WithIpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnets4WithIps not implemented")
}
func (*UnimplementedDhcpServiceServer) GetSubnets6WithIps(context.Context, *GetSubnets6WithIpsRequest) (*GetSubnets6WithIpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnets6WithIps not implemented")
}
func (*UnimplementedDhcpServiceServer) GetSubnet4AndLease4WithIp(context.Context, *GetSubnet4AndLease4WithIpRequest) (*GetSubnet4AndLease4WithIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnet4AndLease4WithIp not implemented")
}
func (*UnimplementedDhcpServiceServer) GetSubnet6AndLease6WithIp(context.Context, *GetSubnet6AndLease6WithIpRequest) (*GetSubnet6AndLease6WithIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnet6AndLease6WithIp not implemented")
}
func (*UnimplementedDhcpServiceServer) GetSubnets4AndLeases4WithIps(context.Context, *GetSubnets4AndLeases4WithIpsRequest) (*GetSubnets4AndLeases4WithIpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnets4AndLeases4WithIps not implemented")
}
func (*UnimplementedDhcpServiceServer) GetSubnets6AndLeases6WithIps(context.Context, *GetSubnets6AndLeases6WithIpsRequest) (*GetSubnets6AndLeases6WithIpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubnets6AndLeases6WithIps not implemented")
}

func RegisterDhcpServiceServer(s *grpc.Server, srv DhcpServiceServer) {
	s.RegisterService(&_DhcpService_serviceDesc, srv)
}

func _DhcpService_GetSubnet4WithIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnet4WithIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnet4WithIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnet4WithIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnet4WithIp(ctx, req.(*GetSubnet4WithIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_GetSubnet6WithIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnet6WithIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnet6WithIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnet6WithIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnet6WithIp(ctx, req.(*GetSubnet6WithIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_GetSubnets4WithIps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnets4WithIpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnets4WithIps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnets4WithIps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnets4WithIps(ctx, req.(*GetSubnets4WithIpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_GetSubnets6WithIps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnets6WithIpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnets6WithIps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnets6WithIps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnets6WithIps(ctx, req.(*GetSubnets6WithIpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_GetSubnet4AndLease4WithIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnet4AndLease4WithIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnet4AndLease4WithIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnet4AndLease4WithIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnet4AndLease4WithIp(ctx, req.(*GetSubnet4AndLease4WithIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_GetSubnet6AndLease6WithIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnet6AndLease6WithIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnet6AndLease6WithIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnet6AndLease6WithIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnet6AndLease6WithIp(ctx, req.(*GetSubnet6AndLease6WithIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_GetSubnets4AndLeases4WithIps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnets4AndLeases4WithIpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnets4AndLeases4WithIps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnets4AndLeases4WithIps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnets4AndLeases4WithIps(ctx, req.(*GetSubnets4AndLeases4WithIpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_GetSubnets6AndLeases6WithIps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubnets6AndLeases6WithIpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetSubnets6AndLeases6WithIps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DhcpService/GetSubnets6AndLeases6WithIps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetSubnets6AndLeases6WithIps(ctx, req.(*GetSubnets6AndLeases6WithIpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DhcpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DhcpService",
	HandlerType: (*DhcpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubnet4WithIp",
			Handler:    _DhcpService_GetSubnet4WithIp_Handler,
		},
		{
			MethodName: "GetSubnet6WithIp",
			Handler:    _DhcpService_GetSubnet6WithIp_Handler,
		},
		{
			MethodName: "GetSubnets4WithIps",
			Handler:    _DhcpService_GetSubnets4WithIps_Handler,
		},
		{
			MethodName: "GetSubnets6WithIps",
			Handler:    _DhcpService_GetSubnets6WithIps_Handler,
		},
		{
			MethodName: "GetSubnet4AndLease4WithIp",
			Handler:    _DhcpService_GetSubnet4AndLease4WithIp_Handler,
		},
		{
			MethodName: "GetSubnet6AndLease6WithIp",
			Handler:    _DhcpService_GetSubnet6AndLease6WithIp_Handler,
		},
		{
			MethodName: "GetSubnets4AndLeases4WithIps",
			Handler:    _DhcpService_GetSubnets4AndLeases4WithIps_Handler,
		},
		{
			MethodName: "GetSubnets6AndLeases6WithIps",
			Handler:    _DhcpService_GetSubnets6AndLeases6WithIps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dhcp.proto",
}
